# This is a basic workflow to help you get started with Actions

name: Update Database Classes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Push directory to another repository
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        REPO: fourjr/rainboard
        SOURCE: ext/database.py
        DESTINATION: core/database.py
      run: |
        git config --local user.email "action@github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git clone "https://$API_TOKEN_GITHUB@github.com/$REPO.git" "clone"
        
        cp "$GITHUB_WORKSPACE/$SOURCE" "clone/$DESTINATION"

        cd clone
        
        DIFF=$(git diff "$DESTINATION")
        echo $DIFF
        if [ -n "$DIFF" ];
        then
          git add $DESTINATION
          git commit --message "Update $DESTINATION (https://github.com/$REPO/commit/$GITHUB_SHA))"
          git push origin master
        fi
